### ISSUE TITLE
Exception Thrown "An item with the same key has already been added"

### ISSUE THREAD

**Issue by joelmleo** [BloodHoundAD/SharpHound3#11]
Aloha folks

I'm attempting to collect data with the latest version of Sharphound (both the .exe and .ps1) and I'm receiving the exception noted in the title: System.ArgumentException: An item with the same key has already been added.

Environment is a Windows Server 2016 forest with 3 single-domain trees:
Forest Root: foo.net
Tree 2: foobar.net
Tree 3: foobarfoo.net

Ingestor (both .exe and .ps1) was executed from a workstation and a server, both fully whitelisted by AV/EDR, with the following command line:
SharpHound.exe --collectionmethod all,gpolocalgroup --collectallproperties --prettyjson --domain foobar.net --throttle 100 --invalidatecache

I tried a number of other options, including running --collectionmethod dconly or removing --collectionmethod entirely, removing --collectallproperties, --throttle, without --invalidatecache, verbose, and against all 3 of the domains in the forest, with and without the admin token, in powershell or at the command prompt, with close to the same results. The ingestor processes for a bit, generates a few JSON files and populates them with a number of entries, then dies with the exception noted without completing the JSON files or generating the .zip. Verbose did not provide anything that helped me identify the issue.

Stack trace as received at the command prompt is attached:
[bloodhound_ERROR.txt](https://github.com/BloodHoundAD/SharpHound3/files/4929293/bloodhound_ERROR.txt)

Thanks, and aloha!

Joel

**Comment by rvazarkar** [comment]
This should be fixed now
