### ISSUE TITLE
[Feature Request] Display status information while collecting data

### ISSUE THREAD

**Issue by TealAlex** [BloodHoundAD/SharpHound3#13]
Hi,
it would be great if Sharphound would show a status bar or other progression information while collecting data. 
Especially in large environments it can take some time and you don't know if something went wrong and Sharphound just hangs or it is still collecting data. 

Following our discussion in Slack something along the lines of ldapsearch can be used:

$ ./ldapsearch --port 1389 --bindDN "cn=Directory Manager" --bindPassword password --baseDN ou=people,dc=example,dc=com --searchScope base "(objectclass=*)" 
numsubordinates

Regards Alex

**Comment by rvazarkar** [comment]
We're displaying status updates, just not total number of objects as this would require us to double our LDAP search
