### ISSUE TITLE
LAPS collection not working

### ISSUE THREAD

**Issue by TealAlex** [BloodHoundAD/SharpHound3#15]
Hi,
the laps edge collection does not work in an environment I'm in.
We started the collection from a PowerShell script as follows
Start-Process $SharphoundBin -ArgumentList "-c all --outputdirectory `"$BloodhoundOutDir`" --loop true --loopduration 02:00:00 --loopinterval 00:10:00" -RedirectStandardOutput sharphound_log.txt

![2020-08-06](https://user-images.githubusercontent.com/52507509/89571409-e70e0000-d827-11ea-82c3-312274c0e570.png)
![laps1](https://user-images.githubusercontent.com/52507509/89571412-e7a69680-d827-11ea-9085-34f49dddf09f.PNG)
![laps2](https://user-images.githubusercontent.com/52507509/89571413-e83f2d00-d827-11ea-92f8-1bd705ac4439.PNG)
![laps3](https://user-images.githubusercontent.com/52507509/89571414-e83f2d00-d827-11ea-9092-04a9cb25e361.PNG)
![laps4](https://user-images.githubusercontent.com/52507509/89571777-87642480-d828-11ea-9b26-dea80001d7f6.PNG)

**Comment by cnotin** [comment]
Hi @TealAlex,
I think I encountered the same problem as you and I suggested a fix in #20
If you can try again with my changes I would be happy to have your feedback!

**Comment by TealAlex** [comment]
Hi, 
great to hear. Unfortunately, I cannot test this as I have no access to that environment anymore.
Regards
Alex

**Comment by cnotin** [comment]
Thanks for your reply. Of course I understand!
