### ISSUE TITLE
[Suggestion] Remove "ComputerId" attribute from "Sessions" in computers.csv as it is redundant

### ISSUE THREAD

**Issue by cnotin** [BloodHoundAD/SharpHound3#23]
A computer object in computers.json looks like this:
```json
{
  "Properties": {
[...]
    "objectid": "S-1-5-21-xxxx-999",
[...]
  "Sessions": [
    {
      "UserId": "S-1-5-21-xxxxxx-123",
      "ComputerId": "S-1-5-21-xxxx-999"
    },
    {
      "UserId": "S-1-5-21-xxxxxx-456",
      "ComputerId": "S-1-5-21-xxxx-999"
    },
[...]
```

The `ComputerId` attribute is repeated for each session and it is redundant with the `objectid` of the computer which we already know (except if I missed a specific case?). I suggest removing it then to have a smaller file :)

**Comment by rvazarkar** [comment]
Running NetSessionEnum against a DC will give you sessions for systems that aren't the DC for example. The ComputerID comes from resolving the computer name that comes back from NetSessionEnum.

**Comment by cnotin** [comment]
Of course it makes sense! Perhaps I made a mistake when looking at the output, or I had an odd case, but I just confirmed that we have ComputerId != ObjectIdentifier in the output so it's all good
Sorry @rvazarkar!
