### ISSUE TITLE
Powershell version doesn't continue after creating schema map

### ISSUE THREAD

**Issue by bluecanarybe** [BloodHoundAD/SharpHound3#24]
Hi,

I've tried executing Sharphound both using powershell in memory and via the binary.exe file. I've noticed that the scan doesn't continue after creating the schema map as compared to the binary.

Screenshot:

<img width="506" alt="sharphound" src="https://user-images.githubusercontent.com/59455457/99286241-e0385580-2838-11eb-950d-618adcdbe1b3.png">

**Comment by rvazarkar** [comment]
Closing this for now. Reopen if its still an issue
