### ISSUE TITLE
Collection hangs on certain hosts due to GetLoggedOnUsersRegistry()

### ISSUE THREAD

**Issue by cnotin** [BloodHoundAD/SharpHound3#3]
My SharpHound collection hangs on the final steps in certain cases (it lasted many hours). I was able to finish it by killing some SMB connections that seemed to be stuck. It immediately finished its scan.
Here is the kind of stuff I saw in loop in Wireshark:
![image](https://user-images.githubusercontent.com/550823/74836176-26e73680-531f-11ea-9712-f83d0c33715e.png)

It seems that the host responds, but always the same in loop and SharpHound loops forever accordingly...
I was wondering to see what would use "winreg" and I guess it's due to `GetLoggedOnUsersRegistry()` in the Logged On task.

My suggestion would be to implement a timeout in the form of a watchdog that would automatically kill these task after a certain amount of time without progress.

**Comment by cnotin** [comment]
FYI it hangs in `RegistryKey.OpenRemoteBaseKey`
(happy to discuss on slack if you want ;))

**Comment by rvazarkar** [comment]
Guess its fixed!

**Comment by cnotin** [comment]
Hi @rvazarkar FYI I ran a collection recently with the newest version and no hanging issue :)
