### ISSUE TITLE
[question] Authentication artifacts

### ISSUE THREAD

**Issue by h1f0x** [BloodHoundAD/SharpHound3#31]
Hi there,

Just wondering if there are any artifacts on the system remaining after the RPC calls on the remote systems. Since SharpHound is going to use an authenticated session on each system reachable within the domain I would like to know if it leaves critical information on the system after the authentication. 

If I understood the Windows authentication process correctly there is a chance, that Wdigest.dll (or other cacheable authentication routines) is used during the process. If the remote system has not turned off credential caching or simply does not support it yet because of an outdated OS the used credentials would be available for maybe a real attacker to gather/steal later on.

Do you have any insights on this topic? I searched through some Microsoft docs and other sources but was not able to answer this question.

Thank you for your awesome work!

**Comment by andyrobbins** [comment]
Hi there

SharpHound performs a type 3, non-interactive logon when it enumerates information on remote systems. This type of logon does not result in plain-text or NT-formatted credentials being stored on the remote system. If an attacker resides on the remote, enumerated system, they will not have the opportunity to gather plain-text or NT-formatted credentials.

If the attacker is able to bind to port 445 on the enumerated system, they may be able to perform an SMB relay attack or capture the NTLMv2 challenge-response pair. Binding to port 445 in Windows is difficult, but by no means impossible. In the SMB relay scenario, the attacker would relay the authentication attempt to a system that does not enforce SMB signing and would be able to successfully authenticate to that other system as the user running the SharpHound process. This first attack can be mitigated most effectively by enforcing SMB signing on all domain-joined computers. If the attacker captures an NTLMv2 challenge-response pair, they may be able to perform offline cracking of that pair to discover the plain-text password of the account. This attack scenario is best mitigated by using a very strong password for the account (at least 15 characters in length, uses upper/lower/numeric/special characters, not easily guessed).

If the attacker resides on a remote, enumerated system that is trusted for unconstrained delegation, then the attacker can abuse this configuration to craft a forwardable kerberos ticket for the user running SharpHound. This attack is most effectively mitigated by marking the user running SharpHound as "Sensitive and cannot be delegated", or by adding the SharpHound user to the "Protected Users" security group.

**Comment by h1f0x** [comment]
Hi @andyrobbins 

Thank you very much for clarification and the technical deep dive! This is highly appreciated and was very useful.
