### ISSUE TITLE
[Feature request] Collect "whenCreated" attribute

### ISSUE THREAD

**Issue by loganmarchione** [BloodHoundAD/SharpHound3#33]
We have a workflow where we lookup users that have never logged on, but the account is still active. Something like this:
`MATCH (n:User) WHERE n.lastlogontimestamp=-1.0 AND n.enabled=TRUE RETURN n`

It would be nice to have the ability to view the "whenCreated" attribute of the user. Our logic is, if they have never logged in and their account is old, we should look into disabling/removing that account.

Even if this attribute wasn't available in BloodHound's UI, if it was in the collected JSON, that would be helpful, as we could use Neo4j directly.

https://docs.microsoft.com/en-us/windows/win32/adschema/a-whencreated

Thanks!

**Comment by rvazarkar** [comment]
Wouldn't lastlogontimestamp accomplish this?

**Comment by loganmarchione** [comment]
@rvazarkar  - Sorry, I had the wrong example in the issue. I updated it with the correct workflow we're using.

**Comment by rvazarkar** [comment]
Have you tried with the flag here? 

https://github.com/BloodHoundAD/SharpHound3/blob/master/SharpHound3/Options.cs#L117

**Comment by loganmarchione** [comment]
I didn't see that. RTFM 🤦.

Let me try it on a domain and get back to you. Will probably have to wait until next week.

**Comment by loganmarchione** [comment]
Closing this out, we're collecting this data using PowerShell.
