### ISSUE TITLE
False positive CanRDP relationship from GPOLocalGroup option (Cause: Group Policy "Security Filtering"?)

### ISSUE THREAD

**Issue by mark-lowe** [BloodHoundAD/SharpHound3#41]
Firstly, thank you for such a great tool.

I recently noticed that BloodHound was telling me that the "Domain Users" group could RDP to some servers.  This was incorrect.  The Remote Desktop Users group was in fact empty.  The options I used were:

`sharphound.exe --domaincontroller mydc -c DCOnly`

The information had come from a Group Policy linked to a server OU.  Security Filtering had been used in the Group Policy Management tool (click the Group Policy link | Scope | Security Filtering).  

Often Security Filtering is set to Authenticated Users, in which case I believe the policy applies to all computers in the OU.  In my case Security Filtering was set to some specific computer accounts, meaning the policy only applied to those computers.  My best guess is that SharpHound is not taking account of Security Filtering and is applying policy information to all computers in the OU.

I ran SharpHound with sufficient privileges to be able to read all the group policy files.

The policy settings that indicated Domain Users could RDP to hosts was the usual Computer Configuration > Policies > Windows Settings > Security Settings > Restricted Groups.  This information was in turn stored in a GptTmpl.inf file on sysvol in the usual place.  NTFS read permissions were granted on GptTmpl.inf to the computer accounts listed in Security Filtering.  NTFS read permission had not been granted to other servers in the OU for this file.  (I assume everything in the paragraph is normal and expected.  I just wanted to be clear).

To recreate this problem try:
1) Create a Server OU containing 2 servers: SERVER1 and SERVER2
2) Link a policy into the Server OU that grants Domain Users membership of Remote Desktop Users
3) Configure Security Filtering on the policy so that it applies only to SERVER1$
4) Check local Remote Desktop Users group members are as expected (empty for Server2; Domain Users for Server1)
5) Run SharpHound and BloodHound.  Check that BloodHound reports that Domain Users can RDP to both Server1 and Server2.  You may have to run BloodHound with high privileges to be able to read the GptTmpl.inf file from sysvol (e.g. Domain Admin privs).

Data about local group memberships other than Remote Desktop Users are probably affected too.

**Comment by mark-lowe** [comment]
I've since read that this is an acknowledged limitation of bloodhound:

> ...our experience has been that in real enterprise networks, you won’t need to worry about WMI filtering, security filtering, or GpLink order in 95% or more of the situations you run into, but I mention them so you know where to start troubleshooting if your abuse actions aren’t working. We may try to roll those three items into the BloodHound interface in the future...

Ref: https://wald0.com/?p=179

**Comment by rvazarkar** [comment]
Definitely a limitation currently. Hopefully we can fix this in the future. Closing this issue for now
