### ISSUE TITLE
Session Information Missing in Latest Version

### ISSUE THREAD

**Issue by emanuelduss** [BloodHoundAD/SharpHound3#44]
Hi everyone

I hope this is the correct place to drop this question / issue.  A colleague and me discovered some strange behavior when collection user sessions. In the end, it looks like the intentional behavior of SharpHound but I still decided to open this issue.

# Infrastructure Setup

- Deployed in Azure
- AD Domain Joined
- Clients: Windows 10, Version 1909, all updates installed
- Server: Windows Server 2019, Version 1809, all updates installed
- User: The user which executed SharpHound was logged in on the Client and is a regular low-privileged domain user (no local/domain admin privileges).

# Technical Description

SharpHound was started from the client.

When using the latest version of SharpHound (from the BloodHound GitHub repository), no sessions on the WS1 server were found:

![image](https://user-images.githubusercontent.com/438188/138040501-627a5e96-5da0-491a-9fe8-82cacffae9c8.png)

When using an oder version of SharpHound, the following sessions on the WS1 were found:
![image](https://user-images.githubusercontent.com/438188/138040754-f9604c09-d9eb-4498-835e-c37674caf637.png)

The same happened with other sessions on other machines.

To exclude timing issues from the tests, both the new and old version were run 5 times to collection sessions. We could reproduce the behavior. The old version always found more sessions than the latest version. The following screenshot compares the collected sessions from the new and old version:

![image](https://user-images.githubusercontent.com/438188/138042982-e3525250-a949-4a65-9b6f-db169becf894.png)

An analysis using Wireshark showed that the newer version performed less requests from the client to the server. The following traffic was only seen in the old version:

![image](https://user-images.githubusercontent.com/438188/138044025-d2a3ff38-caa7-4459-833a-f6733adae3a5.png)

This session information is collected using the `LoggedOn` collection method:

![image](https://user-images.githubusercontent.com/438188/138044251-2ead128f-b0a3-426e-8970-6f55a3cd214b.png)

The reason is commit https://github.com/BloodHoundAD/SharpHound3/commit/ee437a5e596bf738b91bfae0aa35d2aab3544a8f  by @rvazarkar which removed the call to the `GetLoggedOnUsersRegistry` function from the `LoggedOnTasks`. The commit message from @rvazarkar  also mentions the change with "Remove registry logged on".

The `LoggedOn` collection method does add the "session" edge in BloodHound. The offical documentation only recommends to use the Sessions collection method and not both (https://bloodhound.readthedocs.io/en/latest/data-collection/sharphound.html#the-session-loop-collection-method):

![image](https://user-images.githubusercontent.com/438188/139703719-3b9c03ad-0133-47b9-9f80-532236e9e736.png)

# Question

- Apparently, the `GetLoggedOnUsersRegistry` finds sessions which are otherwise not found. Is there a reason this function call was removed?
- Is there a reason why not performing the `LoggedOn` collection method when collection sessions in a loop (`--loop`) is recommended in the documentation?

Thansk for your answer,

Mänu

_Edit: If you stumbled upon this issue and want to collect session information using LoggedOn via Remote Registry, you can build your own one or try this version here: https://github.com/CompassSecurity/SharpHound3/releases/tag/3-registry_

**Comment by rvazarkar** [comment]
I'll be reintroducing this method into the next version of SharpHound.

**Comment by emanuelduss** [comment]
Nice thank you!

Was there a reason this was disabled? And wouldn't it make sense to run the `LoggedOn` collection method in a loop together with the `Session` method?

**Comment by rvazarkar** [comment]
We had some questions about data accuracy, which turned out to be unfounded.

**Comment by emanuelduss** [comment]
I tested the new SharpHound version and the now all data is correclty colledted.

The issue can be closed.

THX very much 👍
