### ISSUE TITLE
--LDAPFilter/--searchbase usage

### ISSUE THREAD

**Issue by owtdecaf** [BloodHoundAD/SharpHound3#7]
Copying and pasting what I wrote in the BH slack.

Hey, so this is a bit of a continuation of when you were helping me with --LDAPFilter and --ComputerFile the other day. Sorry in advance for the essay.

So, using --ComputerFile ended up not being a viable option for us. When we do hostnames, it just ends up not working for whatever reason. It is probably a DNS issue on our end though. We have similar issues on our real customer network. With WFH being the norm currently, DNS has been on the fritz with all the VPNing and we do not have a good way of getting IPs of our targets from a Red Team perspective.

Either way, it is not a good long-term solution since eventually it won’t be scalable considering the size of our network.

So, I went back to --LDAPFilter since I needed a way to filter my targets by OU still. I attached a picture of what’s in the docs which is an example of pretty much what I wanted to. 

From the Docs:
![ldapfilter_doc](https://user-images.githubusercontent.com/27858029/81843221-d0b01b00-953c-11ea-8613-07968f81b3f9.png)

However, I spent a long time trying to get it to work before I realize what was going on.

 In SharpHound v2, you guys had the option to filter by OU and then removed it for the more generic --LDAPFilter in v3. However, the way you guys filter is with --LDAPFilter basically like doing dsquery * -filter [FILTER].

 When you use --LDAPFilter, it just attaches it to the end of the filter. However, you can’t filter by OUs like that. You have to do something like the following.
```
run dsquery * "OU=New York,DC=Contoso,DC=local" -filter (objectclass=computer) -attr dnshostname distinguishedname adspath -limit 0 -l
```
I attached two more pictures so you can see it in action. The first picture is basically replicating the example in my lab where I want to get everything in "OU=WorkStations,DC=gaia,DC=local" which has 2 objects. It finds 0 objects. 

![1](https://user-images.githubusercontent.com/27858029/81843275-ea516280-953c-11ea-8002-baa7d2c286eb.png)

However, a filter like the following (dnshostname=*GAIA*) should work considering how filtering is done and in this case should return all computer objects in my domain (3 objects), which it does (ignore the filter output, we added that to help debug).

![2](https://user-images.githubusercontent.com/27858029/81843313-f806e800-953c-11ea-9b5f-73dd119c8f38.png)

 So, I don’t like to bring up issues without seeing if solutions already exist and they do! You guys have a --searchbase as an option which can limit it to an OU. However, this is another case where it’s visible in sharpHound if you view the help options, but it’s not in your new wiki nor in github which I checked just in case.

In other words, if we wanted to filter by the OU OU=WorkStations,DC=gaia,DC=local in our lab, you have the following options (the other options in the attached picture don’t affect the point I’m making). Side note, it did not like parenthesis with --searchbase. Assuming it is just how the code is written and adds to the filter. Didn’t check the source code for that though and it’s not a concern either way.

```
sharpHound --searchbase "OU=WorkStations,DC=gaia,DC=local"
```
![3](https://user-images.githubusercontent.com/27858029/81843380-0a812180-953d-11ea-88ed-3bd8f484c167.png)

This will grab everything in that OU including the OU object. In my lab environment, that means the 2 computers and the OU itself. Aka, 3 objects which can be seen in 3.png.
The other option is the following:

```
sharpHound --searchbase "OU=WorkStations,DC=gaia,DC=local" --LDAPFilter "objectclass=computer"
```
![4](https://user-images.githubusercontent.com/27858029/81843392-110f9900-953d-11ea-940a-0bd53b4ba16d.png)

Basically, the same as the previous, but the --LDAPFilter just limits it to computers. Aka, this time you still scan the 2 computers but skip enumerating the OU object itself. Don’t see why you wouldn’t grab the OU object as well, but just throwing this out there. Either way, picture 4.png is a visual example.

Anyway, I just wanted to bring it to your attention for the sake of the docs and maybe it’ll help anyone else who might be in a similar situation.

**Comment by cnotin** [comment]
Hey @owtdecaf thanks for this since I just noticed I had the same issue as you...
What do you think of this PR https://github.com/BloodHoundAD/BloodHound/pull/376 to add SearchBase in the doc?

**Comment by rvazarkar** [comment]
Added to docs
